# Generated by Django 4.2.15 on 2025-01-18 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="password",
        ),
        migrations.RemoveField(
            model_name="account",
            name="username",
        ),
    ]
