# Generated by Django 4.2.15 on 2025-01-18 03:08

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0002_remove_account_password_remove_account_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="password",
            field=models.CharField(
                default="asdf", max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="username",
            field=models.CharField(
                default="asdf",
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
            preserve_default=False,
        ),
    ]
