# Generated by Django 4.2.15 on 2025-01-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0003_account_password_account_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
