from django.db import models
from django.contrib.auth.models import AbstractUser 

class Account(AbstractUser): 
    cover_image = models.ImageField(upload_to='media/cover_images/', blank=True, null=True)    
    profile_image = models.ImageField(upload_to='media/profile_images/', blank=True, null=True) 
    biography = models.TextField(blank=True, null=True) 
    photos = models.ImageField(upload_to='media/photos/', blank=True, null=True)   
    videos = models.FileField(upload_to='media/videos/', blank=True, null=True) 
    tributes = models.ForeignKey('Tribute', on_delete=models.CASCADE, blank=True, null=True)
    serial_number = models.CharField(max_length=100, unique=True, blank = True, null = True) 
    date_of_birth = models.DateField(blank=True, null=True)  
    date_of_death = models.DateField(blank=True, null=True)  
    location = models.CharField(max_length=100, blank=True, null=True) 
    qr_code = models.ImageField(upload_to='media/qr_codes/', blank=True, null=True)

class Tribute(models.Model): 
    title = models.CharField(max_length=100) 
    content = models.TextField() 
    date = models.DateTimeField(auto_now_add=True) 
    likes = models.IntegerField(default=0) 
    dislikes = models.IntegerField(default=0) 
    comments = models.ForeignKey('Comment', on_delete=models.CASCADE) 
    shares = models.IntegerField(default=0) 
    views = models.IntegerField(default=0) 
    tags = models.CharField(max_length=100) 
    location = models.CharField(max_length=100) 
    privacy = models.CharField(max_length=100) 
    status = models.CharField(max_length=100) 
    category = models.CharField(max_length=100) 
    type = models.CharField(max_length=100) 
    link = models.URLField() 
    image = models.ImageField(upload_to='media/tribute_images/') 

class Comment(models.Model): 
    content = models.TextField() 
    date = models.DateTimeField(auto_now_add=True) 
    likes = models.IntegerField(default=0) 
    dislikes = models.IntegerField(default=0) 
    replies = models.ForeignKey('Reply', on_delete=models.CASCADE) 
    shares = models.IntegerField(default=0) 
    views = models.IntegerField(default=0) 
    tags = models.CharField(max_length=100) 
    location = models.CharField(max_length=100) 
    privacy = models.CharField(max_length=100) 
    status = models.CharField(max_length=100) 
    category = models.CharField(max_length=100) 
    type = models.CharField(max_length=100) 
    link = models.URLField() 
    image = models.ImageField(upload_to='media/comment_images/') 

class Reply(models.Model):
    content = models.TextField() 
    date = models.DateTimeField(auto_now_add=True) 
    likes = models.IntegerField(default=0) 
    dislikes = models.IntegerField(default=0) 
    shares = models.IntegerField(default=0) 
    views = models.IntegerField(default=0) 
    tags = models.CharField(max_length=100) 
    location = models.CharField(max_length=100) 
    privacy = models.CharField(max_length=100) 
    status = models.CharField(max_length=100) 
    category = models.CharField(max_length=100) 
    type = models.CharField(max_length=100) 
    link = models.URLField() 
    image = models.ImageField(upload_to='media/reply_images/')